sealed class Routes(val route: String) {
    object Login : Routes("login")
    object Registration : Routes("registration")
    object Forgotten : Routes("forgotten")
    object Home : Routes("home")
    object Calendar : Routes("calendar")
    object EventCreate : Routes("event/create")
    object Forum : Routes("forum")
    object Map : Routes("map")
    object MapCreate : Routes("map/create")
    object Profile : Routes("Profile")
    object Event : Routes("event/{id}")
    object MapInfo : Routes("mapInfo/{id}")
    object ForumPage : Routes("forum/{id}")
    object ForumCreatePost : Routes("forum/createpost")
}